// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgtdA8JR6C2t03iV_neACNUbBMz_vWweU',
    appId: '1:671560784167:android:9cbcef88aecbc1f5a53102',
    messagingSenderId: '671560784167',
    projectId: 'among-us-irl-5ec19',
    storageBucket: 'among-us-irl-5ec19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYypOsbF4xjW6ot3_3QqqxhdhYQ8bBq3w',
    appId: '1:671560784167:ios:f51ac4c50acdb916a53102',
    messagingSenderId: '671560784167',
    projectId: 'among-us-irl-5ec19',
    storageBucket: 'among-us-irl-5ec19.firebasestorage.app',
    iosBundleId: 'me.elec.amongUsIrl',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Wy5fmP8USMhJzMn7fNBFu5jZyedCvbE',
    appId: '1:671560784167:web:424a8d77e7806354a53102',
    messagingSenderId: '671560784167',
    projectId: 'among-us-irl-5ec19',
    authDomain: 'among-us-irl-5ec19.firebaseapp.com',
    storageBucket: 'among-us-irl-5ec19.firebasestorage.app',
    measurementId: 'G-GFRL6HEP46',
  );

}